In [1]:
import numpy as np

In [11]:
N_Array = np.array([[1,2,3],[4,5,6]]) # you need two [[]]!

In [12]:
N_Array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
type(N_Array)

numpy.ndarray

In [16]:
# Formatting changes when numbers are big e.g. 300
N_Array_1 = np.array([[1, 2, 300],[4, 5, 6]])

In [17]:
N_Array_1 # Notice the spacing

array([[  1,   2, 300],
       [  4,   5,   6]])

# Array and Features

In [19]:
integers = np.array([[1, 2, 3, 4], [5, 6, 7, 80]])
integers

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 80]])

In [22]:
floats = np.array([0.0, 0.10, 2.56, 3.14])
floats # note for 0.0 you see 0. 

array([0.  , 0.1 , 2.56, 3.14])

## Dimension, Shape, and Size

- `.ndim` : dimension

- `.shape`: shape; returns a tuple

- `.size`: size i.e. number of elements

In [26]:
integers.ndim # dimension of integers

2

In [27]:
floats.ndim # dimension of floats

1

In [28]:
integers.shape # shape of integers

(2, 4)

In [29]:
floats.shape # shape of floats

(4,)

In [30]:
integers.size # size of integers 

8

In [31]:
floats.size # size of floats

4

In [32]:
# Apply loop
for row in integers:
    print(row)

[1 2 3 4]
[ 5  6  7 80]


In [33]:
# print elements in one line; use end = ""
for i in integers.flat:
    print(i, end = "")

123456780

In [35]:
# without end = ""
for i in integers.flat:
    print(i)

1
2
3
4
5
6
7
80


## Many ways of creating arrays

- `np.ones()`

- `np.zeros()`

- `np.full()`

- `np.arange()`

- `np.linspace()` : The np.linspace function will return a sequence of evenly spaced values on that interval;  default value is 50

- `np.random.randint()`: Return random integers from low (inclusive) to high (exclusive)

In [40]:
# np.zeros()
np.zeros(6) # creates six 0s

array([0., 0., 0., 0., 0., 0.])

In [41]:
# np.ones()
np.ones(5) # creates five 1s

array([1., 1., 1., 1., 1.])

In [42]:
# Matrix of ones
np.ones((5,5), dtype = int) # creates 5by5 matrix of 1s

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
# np.full()
np.full((3,3), 100) # creates 3 by 3 matrix of 100s

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [45]:
# np.arange()
np.arange(1, 10) # does not include the last number

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(10, 1, -1) # go backwards

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [51]:
# np.linspace()
np.linspace(0, 10) # includes the last number

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [52]:
# Change default value
np.linspace(0, 10, num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [54]:
# np.randint()
np.random.randint(1, 20, 5) # random integer between 1 and 19

array([ 7,  7, 18, 17, 19])

### Reshape

In [55]:
np.arange(1, 31).reshape(5, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [56]:
# elements should match with dimension
np.arange(1, 30).reshape(5, 6)

ValueError: cannot reshape array of size 29 into shape (5,6)

In [ ]:
np.arange(1,31).reshape(5)

## Do some Stats!

In [60]:
# toy array
x = np.array(np.arange(1, 15))
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
# sum
x.sum()

105

In [64]:
# max
x.max()

14

In [66]:
# min
x.min()

1

In [67]:
# mean()
x.mean()

7.5

In [68]:
# std()
x.std()

4.031128874149275